### ISSUE TITLE
How to set priority to extend templates???

### ISSUE THREAD

**Issue by celm1990** [tejastank/qweb2#1]
Hello,

On [this examples](https://github.com/tejastank/qweb2/blob/bc96594eaa25ef21512cd41b55a9c7d407abd07a/qweb-test-extend.xml#L5-L30) extended [same template](https://github.com/tejastank/qweb2/blob/bc96594eaa25ef21512cd41b55a9c7d407abd07a/qweb-test-extend.xml#L2), but, how can set specific priority for each template inherited?

**Comment by tejastank** [comment]
Priority as base on how first it appear as first inherited.
